name: Lyso_binding
channels:
    - defaults
    - conda-forge
    - ambermd
dependencies:
    - python=3.6
    - pytraj=2.0.2
    - nglview
    - matplotlib=2.0.2
    - numpy
    - scipy
    - sympy
    - pandas
    - cython
    - ipywidgets=7.0
    - notebook=5.2
    - jupyter=1.0
    - statsmodels=0.8
    - widgetsnbextension=3.0
    - jupyter_contrib_nbextensions=0.3
    - requests=2.18
    - openpyxl=2.4
